version: "3"
services:
  analysis:
    build: dockerfiles/notebook
    volumes:
      - ./:/home/jovyan/work/
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=jupytersecrettokenabhsyd68ay
