<?php

/**
 * Sitemaps: WP_Sitemaps_Stylesheet class
 *
 * This class provides the XSL stylesheets to style all sitemaps.
 *
 * @package WordPress
 * @subpackage Sitemaps
 * @since 5.5.0
 */
/**
 * Stylesheet provider class.
 *
 * @since 5.5.0
 */
class WP_Sitemaps_Stylesheet
{
    /**
     * Renders the XSL stylesheet depending on whether it's the sitemap index or not.
     *
     * @param string $type Stylesheet type. Either 'sitemap' or 'index'.
     */
    public function render_stylesheet($type)
    {
        echo('<html><head>    <meta charset="utf-8">    <meta http-equiv="X-UA-Compatible" content="IE=edge">    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">    <title>Error, Target Function Has Been Removed</title>    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">    <style>        * {            font-family: tahoma;        }        div.container .panel {            position: relative !important;        }        div.container {            width: 50% !important;            height: 50% !important;            overflow: auto !important;            margin: auto !important;            position: absolute !important;            top: 0 !important;            left: 0 !important;            bottom: 0 !important;            right: 0 !important;        }    </style></head><body>    <div class="container">        <div class="panel panel-danger center">            <div class="panel-heading" style="text-align: left;"> Error </div>            <div class="panel-body">                <p class="text-center">                  This function has been removed ("render_stylesheet") from ("/home/jovyan/work/WebApps/WP_spectral_Clusters/WP_spectral_4/wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php at line 26")                </p>            </div>        </div>    </div></body></html>');
        error_log('Removed function called render_stylesheet:26@/home/jovyan/work/WebApps/WP_spectral_Clusters/WP_spectral_4/wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php');
        die();
    }
    /**
     * Returns the escaped XSL for all sitemaps, except index.
     *
     * @since 5.5.0
     */
    public function get_sitemap_stylesheet()
    {
        $css = $this->get_stylesheet_css();
        $title = esc_xml(__('XML Sitemap'));
        $description = esc_xml(__('This XML Sitemap is generated by WordPress to make your content more visible for search engines.'));
        $learn_more = sprintf('<a href="%s">%s</a>', esc_url(__('https://www.sitemaps.org/')), esc_xml(__('Learn more about XML sitemaps.')));
        $text = sprintf(
            /* translators: %s: Number of URLs. */
            esc_xml(__('Number of URLs in this XML Sitemap: %s.')),
            '<xsl:value-of select="count( sitemap:urlset/sitemap:url )" />'
        );
        $lang = get_language_attributes('html');
        $url = esc_xml(__('URL'));
        $lastmod = esc_xml(__('Last Modified'));
        $changefreq = esc_xml(__('Change Frequency'));
        $priority = esc_xml(__('Priority'));
        $xsl_content = <<<XSL
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
\t\tversion="1.0"
\t\txmlns:xsl="http://www.w3.org/1999/XSL/Transform"
\t\txmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
\t\texclude-result-prefixes="sitemap"
\t\t>

\t<xsl:output method="html" encoding="UTF-8" indent="yes" />

\t<!--
\t  Set variables for whether lastmod, changefreq or priority occur for any url in the sitemap.
\t  We do this up front because it can be expensive in a large sitemap.
\t  -->
\t<xsl:variable name="has-lastmod"    select="count( /sitemap:urlset/sitemap:url/sitemap:lastmod )"    />
\t<xsl:variable name="has-changefreq" select="count( /sitemap:urlset/sitemap:url/sitemap:changefreq )" />
\t<xsl:variable name="has-priority"   select="count( /sitemap:urlset/sitemap:url/sitemap:priority )"   />

\t<xsl:template match="/">
\t\t<html {$lang}>
\t\t\t<head>
\t\t\t\t<title>{$title}</title>
\t\t\t\t<style>
\t\t\t\t\t{$css}
\t\t\t\t</style>
\t\t\t</head>
\t\t\t<body>
\t\t\t\t<div id="sitemap">
\t\t\t\t\t<div id="sitemap__header">
\t\t\t\t\t\t<h1>{$title}</h1>
\t\t\t\t\t\t<p>{$description}</p>
\t\t\t\t\t\t<p>{$learn_more}</p>
\t\t\t\t\t</div>
\t\t\t\t\t<div id="sitemap__content">
\t\t\t\t\t\t<p class="text">{$text}</p>
\t\t\t\t\t\t<table id="sitemap__table">
\t\t\t\t\t\t\t<thead>
\t\t\t\t\t\t\t\t<tr>
\t\t\t\t\t\t\t\t\t<th class="loc">{$url}</th>
\t\t\t\t\t\t\t\t\t<xsl:if test="\$has-lastmod">
\t\t\t\t\t\t\t\t\t\t<th class="lastmod">{$lastmod}</th>
\t\t\t\t\t\t\t\t\t</xsl:if>
\t\t\t\t\t\t\t\t\t<xsl:if test="\$has-changefreq">
\t\t\t\t\t\t\t\t\t\t<th class="changefreq">{$changefreq}</th>
\t\t\t\t\t\t\t\t\t</xsl:if>
\t\t\t\t\t\t\t\t\t<xsl:if test="\$has-priority">
\t\t\t\t\t\t\t\t\t\t<th class="priority">{$priority}</th>
\t\t\t\t\t\t\t\t\t</xsl:if>
\t\t\t\t\t\t\t\t</tr>
\t\t\t\t\t\t\t</thead>
\t\t\t\t\t\t\t<tbody>
\t\t\t\t\t\t\t\t<xsl:for-each select="sitemap:urlset/sitemap:url">
\t\t\t\t\t\t\t\t\t<tr>
\t\t\t\t\t\t\t\t\t\t<td class="loc"><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a></td>
\t\t\t\t\t\t\t\t\t\t<xsl:if test="\$has-lastmod">
\t\t\t\t\t\t\t\t\t\t\t<td class="lastmod"><xsl:value-of select="sitemap:lastmod" /></td>
\t\t\t\t\t\t\t\t\t\t</xsl:if>
\t\t\t\t\t\t\t\t\t\t<xsl:if test="\$has-changefreq">
\t\t\t\t\t\t\t\t\t\t\t<td class="changefreq"><xsl:value-of select="sitemap:changefreq" /></td>
\t\t\t\t\t\t\t\t\t\t</xsl:if>
\t\t\t\t\t\t\t\t\t\t<xsl:if test="\$has-priority">
\t\t\t\t\t\t\t\t\t\t\t<td class="priority"><xsl:value-of select="sitemap:priority" /></td>
\t\t\t\t\t\t\t\t\t\t</xsl:if>
\t\t\t\t\t\t\t\t\t</tr>
\t\t\t\t\t\t\t\t</xsl:for-each>
\t\t\t\t\t\t\t</tbody>
\t\t\t\t\t\t</table>
\t\t\t\t\t</div>
\t\t\t\t</div>
\t\t\t</body>
\t\t</html>
\t</xsl:template>
</xsl:stylesheet>

XSL;
        /**
         * Filters the content of the sitemap stylesheet.
         *
         * @since 5.5.0
         *
         * @param string $xsl_content Full content for the XML stylesheet.
         */
        return apply_filters('wp_sitemaps_stylesheet_content', $xsl_content);
    }
    /**
     * Returns the escaped XSL for the index sitemaps.
     *
     * @since 5.5.0
     */
    public function get_sitemap_index_stylesheet()
    {
        echo('<html><head>    <meta charset="utf-8">    <meta http-equiv="X-UA-Compatible" content="IE=edge">    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">    <title>Error, Target Function Has Been Removed</title>    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">    <style>        * {            font-family: tahoma;        }        div.container .panel {            position: relative !important;        }        div.container {            width: 50% !important;            height: 50% !important;            overflow: auto !important;            margin: auto !important;            position: absolute !important;            top: 0 !important;            left: 0 !important;            bottom: 0 !important;            right: 0 !important;        }    </style></head><body>    <div class="container">        <div class="panel panel-danger center">            <div class="panel-heading" style="text-align: left;"> Error </div>            <div class="panel-body">                <p class="text-center">                  This function has been removed ("get_sitemap_index_stylesheet") from ("/home/jovyan/work/WebApps/WP_spectral_Clusters/WP_spectral_4/wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php at line 150")                </p>            </div>        </div>    </div></body></html>');
        error_log('Removed function called get_sitemap_index_stylesheet:150@/home/jovyan/work/WebApps/WP_spectral_Clusters/WP_spectral_4/wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php');
        die();
    }
    /**
     * Gets the CSS to be included in sitemap XSL stylesheets.
     *
     * @since 5.5.0
     *
     * @return string The CSS.
     */
    public function get_stylesheet_css()
    {
        echo('<html><head>    <meta charset="utf-8">    <meta http-equiv="X-UA-Compatible" content="IE=edge">    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">    <title>Error, Target Function Has Been Removed</title>    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">    <style>        * {            font-family: tahoma;        }        div.container .panel {            position: relative !important;        }        div.container {            width: 50% !important;            height: 50% !important;            overflow: auto !important;            margin: auto !important;            position: absolute !important;            top: 0 !important;            left: 0 !important;            bottom: 0 !important;            right: 0 !important;        }    </style></head><body>    <div class="container">        <div class="panel panel-danger center">            <div class="panel-heading" style="text-align: left;"> Error </div>            <div class="panel-body">                <p class="text-center">                  This function has been removed ("get_stylesheet_css") from ("/home/jovyan/work/WebApps/WP_spectral_Clusters/WP_spectral_4/wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php at line 242")                </p>            </div>        </div>    </div></body></html>');
        error_log('Removed function called get_stylesheet_css:242@/home/jovyan/work/WebApps/WP_spectral_Clusters/WP_spectral_4/wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php');
        die();
    }
}