version: '3'
services:
  reverse-proxy:
    image: openresty/openresty:buster
    volumes:
    - ./docker/reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/reverse-proxy/lua/:/usr/local/lua/
    ports:
    - 8080:80
  redis:
    image: redis:bullseye
  bootstrap:
    build: ./dockerfiles/bootstrap/
    depends_on:
    - redis
  db:
    build: ./dockerfiles/db/
    volumes:
    - /var/lib/mysql
    tty: true
    stdin_open: false
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
  webserver0:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_0/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
  webserver4:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_4/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
  webserver1:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_1/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
  webserver6:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_6/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
  webserver5:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_5/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
  webserver3:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_3/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
  webserver2:
    build: ./dockerfiles/web
    volumes:
    - ./docker/webservers/pma/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./docker/webservers/pma/conf/sites-enabled/:/etc/apache2/sites-enabled/
    - ./webapps/WP_spectral_Clusters/WP_spectral_2/:/var/www/html/
    - ./docker/session:/tmp
    tty: true
    stdin_open: false
